### ISSUE TITLE
One Time Password needed twice

### ISSUE THREAD

**Issue by gopsmaheta** [mdobydullah/laravel-2fa-with-google-authenticator#1]
After successfully enable 2FA first time using OPT, it'll ask again to enter OTP when user redirects to the home page or any other page.

**Comment by mdobydullah** [comment]
Hi @gopsmaheta,  Could you please share your code or send me a video? I've tested a few times. It worked perfectly for me.

**Comment by gopsmaheta** [comment]
Hi @mdobydullah,
Thank you for the quick response.

So, I've just cloned your code and followed below commands in order to run an application.
1. Copied .env.example to .env
2. Composer install command
3. artisan key generate and migration
4. Added middleware to home route.

**Problem:** First time when you enable 2FA, you'll need to enter the OTP from authenticator application, after that if you go to the home page, it'll ask again for OTP. Yes, make sure 2fa middleware added to your home route. See image. 
![image](https://user-images.githubusercontent.com/5382952/77500839-386eb180-6e7c-11ea-985d-00546e0e4efc.png)



That's it, no more changes I've done. Please check the [video](https://drive.google.com/open?id=1MqvFAozsDnaSpdV6wHUbENfvle1dwdTU) or let me know if still anything unclear.
URL: [Video link](https://drive.google.com/open?id=1MqvFAozsDnaSpdV6wHUbENfvle1dwdTU)

And again thank you. :)

**Comment by mdobydullah** [comment]
Hello @gopsmaheta,

Thanks for clearing me. I understand. Google Auth has two options.

1. 2FA settings option. By using this, user can enable/disable 2FA on his/her account.
2. Verify 2FA (middleware). This is used to protect any route to direct access. Admin can set protection in any route or any route group. From your code, I've seen that you've protected ```home``` route with 2FA. So, the user needs to enter OTP to access home route.

Now, let's take a look at the routes.  These routes are for 2FA settings:
```
Route::group(['prefix'=>'2fa'], function(){
    Route::get('/','LoginSecurityController@show2faForm');
    Route::post('/generateSecret','LoginSecurityController@generate2faSecret')->name('generate2faSecret');
    Route::post('/enable2fa','LoginSecurityController@enable2fa')->name('enable2fa');
    Route::post('/disable2fa','LoginSecurityController@disable2fa')->name('disable2fa');

    // 2fa middleware (verify OTP)
    Route::post('/2faVerify', function () {
        return redirect(URL()->previous());
    })->name('2faVerify')->middleware('2fa');
});
```
And in this route, you have set protection:
```
Route::get('/home', 'HomeController@index')->name('home')->middleware('2fa');
```
That's it. If you have more confusions,  let me know. I'll try to understand you in different way.

Happy coding... :)

**Comment by gopsmaheta** [comment]
Hey, thank you for the brief explanation. I got your point with two options. BUT,

When we enable 2fa, that time we enter OTP, and then when we back to the home page, again we enter OTP. 

So what if when we enabled 2fa using OPT, then it shouldn't ask for OTP again on home page, because we already entered while enabling it, then why a second time?

In short, when you use OPT from the application while you enabling 2fa, it shouldn't ask for the second time. If we can store that OTP in session or anywhere?  

Your help truly appreciated.

**Comment by mdobydullah** [comment]
Yeah, normally when we enable OTP in another application, it won't ask. Because they set OTP on the login page. For testing purposes, I've shown the uses of OTP in test route.

I've just described the uses of OTP in my article. Now you can use the OTP protection anywhere. If you set OTP after successful login, then the application will ask for OTP after login only.
